##### IsoTV Config File

pipeline: "IsoTV"
repo: "https://github.molgen.mpg.de/MayerGroup/IsoTV"

### Ouput directory

outdir: "/project/owlmayerTemporary/Sid/isoform_analysis/github"

### General pipeline parameters:

basecalling: FALSE
preprocess: FALSE
annotation: TRUE
quantification: TRUE

###### ONT long read processing config
### Basecalling pipeline parameters

guppy: "/path/to/Guppy324/bin/guppy_basecaller"
flowcell: FLO-MIN106
kit: SQK-DCS109

### Reference Files

genome_fasta: "/project/owlmayerTemporary/Sid/nanopore-analysis/ReferenceData/GRCh38.p12.primary_assembly.genome.fa"
genome_annot: "/project/owlmayerTemporary/Sid/nanopore-analysis/ReferenceData/gencode.v32.primary_assembly.annotation.gtf"

### Samples
# samples with .bottom extension must be placed in the RawData folder
# condition_replicate
samples:
    day5_1: "OJ32"
    day0_1: "OJ33"
    day3_1: "OJ34"
    day0_2: "OJ40"
    day5_2: "OJ41"
    day3_2: "OJ42"
    day0_3: "OJ54"
    day3_3: "OJ55"
    day5_5: "OJ56"

threads: 16

# Use pychopper results
pychopper: TRUE

# Use annotation to improve splice junction mapping (minimap2 --junc_bed parameter)
minimap2_opts_junction: TRUE

# Minimum read quality to keep:
min_mean_q: 5

# Stringency of porechop heuristic:
porechop_heu_stringency: 0.25

# Options passed to minimap2 during indexing:
minimap2_index_opts: "-k14"

# Extra options passed to minimap2:
minimap2_opts: "-uf"  # required for stranded data e.g. when pychopper filtered

# Minmum mapping quality:
minimum_mapping_quality: 5

# Options passed to spliced_bam2gff:
spliced_bam2gff_opts: "-s"  # required for stranded data e.g. when pychopper filtered

# -c parameter:
minimum_cluster_size: 3

# -p parameter:
minimum_isoform_percent: 1

# -d parameter:
exon_boundary_tolerance: 10

# -e parameter:
terminal_exon_boundary_tolerance: 50

# Extra options passed to minimap2 when mapping polished reads:
minimap2_opts_polished: "-uf"   # required for stranded data e.g. when pychopper filtered

# Options passed to spliced_bam2gff when converting alignments of polished reads:
spliced_bam2gff_opts_pol: "-s"  # required for stranded data e.g. when pychopper filtered

# Options passed to collapse_partials when collapsing fragmentation artifacts
# Internal exon boundary tolerance:
collapse_internal_tol: 5

# Five prime boundary tolerance:
collapse_five_tol: 500

# Three prime boundary tolerance:
collapse_three_tol: 50

maximum_secondary: 200
secondary_score_ratio: 1

##### Feature Analysis Config
### Input genestt

gene_file: "/home/annaldas/projects/IsoTV/genes.tab"

### Output file and folder

output_plots: "test.pdf"

### Processed file paths - required if not using ONT long read processing workflow

#nanopore_gtf: "/project/owlmayerTemporary/Sid/gencode/gencode.v32.primary_assembly.annotation.gtf"
#nanopore_gtf: "/project/owlmayerTemporary/Sid/isoform_analysis/goeke/Results/GffCompare/nanopore.combined.gtf"
#polished_reads: "/project/owlmayerTemporary/Sid/gencode/gencode.v32.pc_transcripts.fa"
#polished_reads: "/project/owlmayerTemporary/Sid/ForOlga/Sequence/OlgaGenes.fa"
#counts_data: "/project/owlmayerTemporary/Sid/ForOlga/Sequence/OlgaGenes.fa"
#counts_data: "data/test.txt"

nanopore_gtf: "/project/owlmayerTemporary/Sid/isoform_analysis/github/Results/GffCompare/nanopore.combined.gtf"
polished_reads: "/project/owlmayerTemporary/Sid/isoform_analysis/github/Results/Pinfish/corrected_transcriptome_polished_collapsed_nonredundant_tcons.fas"
counts_data: "/project/owlmayerTemporary/Sid/isoform_analysis/github/Results/Quantification/counts_deseq2norm.txt"

# Is data continuous
continuous: TRUE

### External tool paths and functional analysis

aa: TRUE

#iupred2a_path: "/path/to/iupred2a/iupred2a.py"
iupred2a_path: "/home/annaldas/iupred2a/iupred2a.py"
iupred2a: TRUE

#brewery_path: "/path/to/Brewery/Brewery.py"
brewery_path: "/home/annaldas/Brewery/Brewery.py"
brewery: FALSE

pfam: TRUE

#prositeScan_path: "/path/to/ps_scan/ps_scan.pl"
#pfScan_path: "/path/to/ps_scan/pfscan"
#prositeDat_path: "/path/to/prosite.dat"
prositeScan_path: "/home/annaldas/ps_scan/ps_scan.pl"
pfScan_path: "/home/annaldas/ps_scan/pfscan"
prositeDat_path: "/project/owlmayerTemporary/Sid/github/prosite.dat"
pfScan: TRUE

minIsoTPM: 0
maxIsoNum: 8
minIsoPct: 0
